/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmer_Instance */

#ifndef _Included_org_wasmer_Instance
#define _Included_org_wasmer_Instance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmer_Instance
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wasmer_Instance_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
