/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmer_Memory */

#ifndef _Included_org_wasmer_Memory
#define _Included_org_wasmer_Memory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmer_Memory
 * Method:    nativeMemoryView
 * Signature: (Lorg/wasmer/Memory;J)V
 */
JNIEXPORT void JNICALL Java_org_wasmer_Memory_nativeMemoryView
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_wasmer_Memory
 * Method:    nativeMemoryGrow
 * Signature: (Lorg/wasmer/Memory;JI)I
 */
JNIEXPORT jint JNICALL Java_org_wasmer_Memory_nativeMemoryGrow
  (JNIEnv *, jobject, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
