/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmer_Memory */

#ifndef _Included_org_wasmer_Memory
#define _Included_org_wasmer_Memory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmer_Memory
 * Method:    nativeSetMemoryData
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_wasmer_Memory_nativeSetMemoryData
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
