/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmer_Module */

#ifndef _Included_org_wasmer_Module
#define _Included_org_wasmer_Module
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmer_Module
 * Method:    nativeModuleInstantiate
 * Signature: (Lorg/wasmer/Module;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_wasmer_Module_nativeModuleInstantiate
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     org_wasmer_Module
 * Method:    nativeDrop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wasmer_Module_nativeDrop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wasmer_Module
 * Method:    nativeValidate
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wasmer_Module_nativeValidate
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
