/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wasmer_Instance */

#ifndef _Included_org_wasmer_Instance
#define _Included_org_wasmer_Instance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wasmer_Instance
 * Method:    instantiate
 * Signature: (Lorg/wasmer/Instance;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_wasmer_Instance_instantiate
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     org_wasmer_Instance
 * Method:    drop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_wasmer_Instance_drop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_wasmer_Instance
 * Method:    dynCall
 * Signature: (JLjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_org_wasmer_Instance_dynCall
  (JNIEnv *, jobject, jlong, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
